### ISSUE TITLE
Link to the Live Demo is broken

### ISSUE THREAD

**Issue by paulklemm** [rodrigonogueira4/BusData#1]
The link to the live demo in the Readme.md is broken: [https://github.com/rodrigonogueira4/BusData](https://github.com/rodrigonogueira4/BusData). Can you fix it please? :+1:

**Comment by rodrigonogueira4** [comment]
Fixed :)
I noticed that the most of the days are broken. Please use 12/18/2013 as an sample while we try to fix the remaining days.

**Comment by paulklemm** [comment]
Thanks! It seems that there is still something off, tried loading 12/18/2013 but it gives errors. Tried Chrome and Firefox.
![screen-shot-2015-10-28-17-33-11-90c6wkkmjr](https://cloud.githubusercontent.com/assets/2169489/10805228/81adce80-7dcc-11e5-973d-7556cb9c0c54.png)

Please do not invest too much time if this is not trivial to fix, I just want to try the tool real quick because I liked your VisWeek presentation.

**Comment by rodrigonogueira4** [comment]
Thanks for pointing this out!
If you try to access using only 'http' instead of 'https' it should work:
http://rodrigonogueira4.github.io/BusData/Outlier_Vis/index.html

![screenshot from 2015-10-28 18 46 26](https://cloud.githubusercontent.com/assets/2531204/10805485/6877899c-7da4-11e5-95f0-4f6646a40cb1.png)

**Comment by paulklemm** [comment]
Cool thanks. Great work! :+1:
